/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsGettingStartedIndexRouteImport } from './routes/docs/getting-started/index'
import { Route as DocsComponentsIndexRouteImport } from './routes/docs/components/index'
import { Route as DocsBuildingYourAppIndexRouteImport } from './routes/docs/building-your-app/index'
import { Route as DocsGettingStartedInstallationRouteImport } from './routes/docs/getting-started/installation'
import { Route as DocsComponentsAvatarRouteImport } from './routes/docs/components/avatar'
import { Route as DocsBuildingYourAppThemingRouteImport } from './routes/docs/building-your-app/theming'
import { Route as DocsBuildingYourAppStylingRouteImport } from './routes/docs/building-your-app/styling'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsGettingStartedIndexRoute = DocsGettingStartedIndexRouteImport.update({
  id: '/getting-started/',
  path: '/getting-started/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsComponentsIndexRoute = DocsComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsBuildingYourAppIndexRoute =
  DocsBuildingYourAppIndexRouteImport.update({
    id: '/building-your-app/',
    path: '/building-your-app/',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsGettingStartedInstallationRoute =
  DocsGettingStartedInstallationRouteImport.update({
    id: '/getting-started/installation',
    path: '/getting-started/installation',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsComponentsAvatarRoute = DocsComponentsAvatarRouteImport.update({
  id: '/components/avatar',
  path: '/components/avatar',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsBuildingYourAppThemingRoute =
  DocsBuildingYourAppThemingRouteImport.update({
    id: '/building-your-app/theming',
    path: '/building-your-app/theming',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsBuildingYourAppStylingRoute =
  DocsBuildingYourAppStylingRouteImport.update({
    id: '/building-your-app/styling',
    path: '/building-your-app/styling',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/docs/': typeof DocsIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/docs/building-your-app/styling': typeof DocsBuildingYourAppStylingRoute
  '/docs/building-your-app/theming': typeof DocsBuildingYourAppThemingRoute
  '/docs/components/avatar': typeof DocsComponentsAvatarRoute
  '/docs/getting-started/installation': typeof DocsGettingStartedInstallationRoute
  '/docs/building-your-app': typeof DocsBuildingYourAppIndexRoute
  '/docs/components': typeof DocsComponentsIndexRoute
  '/docs/getting-started': typeof DocsGettingStartedIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/docs/building-your-app/styling': typeof DocsBuildingYourAppStylingRoute
  '/docs/building-your-app/theming': typeof DocsBuildingYourAppThemingRoute
  '/docs/components/avatar': typeof DocsComponentsAvatarRoute
  '/docs/getting-started/installation': typeof DocsGettingStartedInstallationRoute
  '/docs/building-your-app': typeof DocsBuildingYourAppIndexRoute
  '/docs/components': typeof DocsComponentsIndexRoute
  '/docs/getting-started': typeof DocsGettingStartedIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/docs/': typeof DocsIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/docs/building-your-app/styling': typeof DocsBuildingYourAppStylingRoute
  '/docs/building-your-app/theming': typeof DocsBuildingYourAppThemingRoute
  '/docs/components/avatar': typeof DocsComponentsAvatarRoute
  '/docs/getting-started/installation': typeof DocsGettingStartedInstallationRoute
  '/docs/building-your-app/': typeof DocsBuildingYourAppIndexRoute
  '/docs/components/': typeof DocsComponentsIndexRoute
  '/docs/getting-started/': typeof DocsGettingStartedIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs/'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/docs/building-your-app/styling'
    | '/docs/building-your-app/theming'
    | '/docs/components/avatar'
    | '/docs/getting-started/installation'
    | '/docs/building-your-app'
    | '/docs/components'
    | '/docs/getting-started'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/docs/building-your-app/styling'
    | '/docs/building-your-app/theming'
    | '/docs/components/avatar'
    | '/docs/getting-started/installation'
    | '/docs/building-your-app'
    | '/docs/components'
    | '/docs/getting-started'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/docs/'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/docs/building-your-app/styling'
    | '/docs/building-your-app/theming'
    | '/docs/components/avatar'
    | '/docs/getting-started/installation'
    | '/docs/building-your-app/'
    | '/docs/components/'
    | '/docs/getting-started/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/getting-started/': {
      id: '/docs/getting-started/'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/components/': {
      id: '/docs/components/'
      path: '/components'
      fullPath: '/docs/components'
      preLoaderRoute: typeof DocsComponentsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/building-your-app/': {
      id: '/docs/building-your-app/'
      path: '/building-your-app'
      fullPath: '/docs/building-your-app'
      preLoaderRoute: typeof DocsBuildingYourAppIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/getting-started/installation': {
      id: '/docs/getting-started/installation'
      path: '/getting-started/installation'
      fullPath: '/docs/getting-started/installation'
      preLoaderRoute: typeof DocsGettingStartedInstallationRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/components/avatar': {
      id: '/docs/components/avatar'
      path: '/components/avatar'
      fullPath: '/docs/components/avatar'
      preLoaderRoute: typeof DocsComponentsAvatarRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/building-your-app/theming': {
      id: '/docs/building-your-app/theming'
      path: '/building-your-app/theming'
      fullPath: '/docs/building-your-app/theming'
      preLoaderRoute: typeof DocsBuildingYourAppThemingRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/building-your-app/styling': {
      id: '/docs/building-your-app/styling'
      path: '/building-your-app/styling'
      fullPath: '/docs/building-your-app/styling'
      preLoaderRoute: typeof DocsBuildingYourAppStylingRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteRouteChildren {
  DocsIndexRoute: typeof DocsIndexRoute
  DocsBuildingYourAppStylingRoute: typeof DocsBuildingYourAppStylingRoute
  DocsBuildingYourAppThemingRoute: typeof DocsBuildingYourAppThemingRoute
  DocsComponentsAvatarRoute: typeof DocsComponentsAvatarRoute
  DocsGettingStartedInstallationRoute: typeof DocsGettingStartedInstallationRoute
  DocsBuildingYourAppIndexRoute: typeof DocsBuildingYourAppIndexRoute
  DocsComponentsIndexRoute: typeof DocsComponentsIndexRoute
  DocsGettingStartedIndexRoute: typeof DocsGettingStartedIndexRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsIndexRoute: DocsIndexRoute,
  DocsBuildingYourAppStylingRoute: DocsBuildingYourAppStylingRoute,
  DocsBuildingYourAppThemingRoute: DocsBuildingYourAppThemingRoute,
  DocsComponentsAvatarRoute: DocsComponentsAvatarRoute,
  DocsGettingStartedInstallationRoute: DocsGettingStartedInstallationRoute,
  DocsBuildingYourAppIndexRoute: DocsBuildingYourAppIndexRoute,
  DocsComponentsIndexRoute: DocsComponentsIndexRoute,
  DocsGettingStartedIndexRoute: DocsGettingStartedIndexRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
